<?php
/*
 * File generated by ModulesGarden packages system
 * 
 * Below you can find current version & revision of this module
 */

$moduleVersion = '1.2.10';
$moduleRevision = 'ee4abed97f7fff6b51417ec2a3aafad9ab6c367e';
$moduleWikiUrl = 'https://www.docs.modulesgarden.com/Abandoned_Cart_For_WHMCS';
$moduleHash='c749f997090ebe4efae17e8901502a21ee6b31ca';