<?php
/*
 * File generated by ModulesGarden packages system
 * 
 * Below you can find current version & revision of this module
 */

$moduleVersion = '1.2.10';
$moduleRevision = 'ee4abed97f7fff6b51417ec2a3aafad9ab6c367e';
$moduleWikiUrl = 'https://www.docs.modulesgarden.com/Abandoned_Cart_For_WHMCS';
$moduleHash='dbbb3fc20f1dd86546c0b3c7919d84c33dd8059d';